
name: test
on:
  schedule:
    - cron:  '1 * * * *'
  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -  name: Compile
         run: |
            javac Hello.java
      -   name: Exe
          run:  
            java Hello
