
name: test
on:
  push:
  
  workflow_dispatch:
  
jobs:
    
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -  name: Compile
         run: |
            javac Hello.java
  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -  name: Exe
         run: |
            java Hello
