
name: test
on:
  push:
  
  workflow_dispatch:
  
jobs:
    
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -  name: Compile
         run: |
            javac Hello.java
            java Hello
  job2:
   needs: job1
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v2
      -  name: Exe
         run: |
            javac Hello.java
            java Hello
